# Generated by Django 6.1.1 on 2026-09-24 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verticals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=20, unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-starts_on'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='one_current_academic_year'), models.CheckConstraint(condition=models.Q(('ends_on__gt', models.F('starts_on'))), name='academic_year_ends_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='verticals.vertical')),
            ],
            options={
                'ordering': ['-academic_year__starts_on', 'vertical__display_order'],
                'indexes': [models.Index(fields=['academic_year', 'vertical'], name='memberships_academi_49ae79_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'vertical', 'academic_year'), name='one_membership_per_user_vertical_year'), models.CheckConstraint(condition=models.Q(models.Q(('left_at__isnull', True), ('status', 'active')), models.Q(('left_at__isnull', False), ('status', 'ended')), _connector='OR'), name='membership_status_matches_left_at')],
            },
        ),
    ]
