# Generated by Django 6.1.1 on 2026-09-24 19:38

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='PSGIM E-Cell', max_length=200)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64, validators=[apps.core.models.validate_timezone])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'organization settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='organization_settings_singleton')],
            },
        ),
    ]
