# Generated by Django 6.1.1 on 2026-09-28 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verticals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlockType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('json_schema', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_parent_keys', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('content_type', models.CharField(blank=True, choices=[('page', 'Page'), ('initiative', 'Initiative'), ('nec', 'Nec'), ('event', 'Event'), ('blog', 'Blog')], default='', max_length=20)),
                ('event_kind', models.CharField(blank=True, default='', max_length=80)),
                ('stages', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='verticals.vertical')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('page', 'Page'), ('initiative', 'Initiative'), ('nec', 'Nec'), ('event', 'Event'), ('blog', 'Blog')], max_length=20)),
                ('slug', models.SlugField(max_length=140)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('unpublish_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='verticals.vertical')),
            ],
            options={
                'ordering': ['content_type', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('cover', models.URLField(blank=True)),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.URLField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('author_vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verticals.vertical')),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_detail', to='content.contentitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('blocks', models.JSONField(default=dict)),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('change_note', models.CharField(blank=True, max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_versions', to=settings.AUTH_USER_MODEL)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.contentitem')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='draft_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.contentversion'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.contentversion'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_index', models.PositiveIntegerField()),
                ('stage_kind', models.CharField(max_length=20)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes Requested')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_approvals', to=settings.AUTH_USER_MODEL)),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='content.contentversion')),
            ],
            options={
                'ordering': ['content_version', 'stage_index'],
            },
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, max_length=80)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_detail', to='content.contentitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitiativeDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('stage', models.CharField(blank=True, max_length=120)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_detail', to='content.contentitem')),
                ('lead_vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verticals.vertical')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloudinary_public_id', models.CharField(max_length=300)),
                ('delivery_url', models.URLField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('owner_vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verticals.vertical')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NECDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('edition', models.CharField(blank=True, max_length=60)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nec_detail', to='content.contentitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.URLField(blank=True)),
                ('content_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_detail', to='content.contentitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='contentversion',
            index=models.Index(fields=['content_item', 'state'], name='content_con_content_fc13e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.UniqueConstraint(fields=('content_item', 'number'), name='unique_version_number_per_item'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['state', 'publish_at'], name='content_con_state_b04fa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentitem',
            constraint=models.UniqueConstraint(fields=('content_type', 'slug'), name='unique_slug_per_content_type'),
        ),
    ]
