# Generated by Django 6.1.1 on 2026-09-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='approval_stages_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
