# Generated by Django 6.1.1 on 2026-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentversion_approval_stages_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='author_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='audience',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='registration_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='summary',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='time_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='turnout',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
