# Generated by Django 6.1.1 on 2026-10-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_blogdetail_author_name_blogdetail_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='source',
            field=models.CharField(blank=True, help_text="e.g. 'linkedin', 'official_pdf', 'manual'.", max_length=40),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='speakers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
