# Generated by Django 6.1.1 on 2026-10-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_eventdetail_linkedin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='related_initiative',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
