# Generated by Django 6.1.1 on 2026-10-01 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('programme_or_year', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('navbar', 'Navbar'), ('home', 'Home'), ('about', 'About'), ('nec', 'Nec')], default='direct', max_length=20)),
                ('handled', models.BooleanField(default=False)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='join_joinsu_created_597d27_idx'), models.Index(fields=['handled', '-created_at'], name='join_joinsu_handled_bb5544_idx'), models.Index(fields=['email'], name='join_joinsu_email_4ebfe8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('handled', False), ('handled_at__isnull', True)), models.Q(('handled', True), ('handled_at__isnull', False)), _connector='OR'), name='join_submission_handled_matches_handled_at')],
            },
        ),
    ]
