# Generated by Django 6.1.1 on 2026-09-24 19:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_privileged', models.BooleanField(default=False)),
                ('assign_permission', models.ForeignKey(default='role.assign', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rbac.permission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_only', models.BooleanField(default=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rbac.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.role')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='rbac.RolePermission', to='rbac.permission'),
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('VERTICAL', 'Vertical'), ('EVENT', 'Event'), ('PROJECT', 'Project')], max_length=10)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='memberships.academicyear')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='rbac_roleas_user_id_a63ff0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('scope_id__isnull', True), ('scope_type', 'GLOBAL')), models.Q(models.Q(('scope_type', 'GLOBAL'), _negated=True), ('scope_id__isnull', False)), _connector='OR'), name='assignment_scope_id_matches_type'), models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='assignment_ends_after_start'), models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'role', 'scope_type', 'scope_id'), name='one_live_assignment_per_user_role_scope', nulls_distinct=False)],
            },
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
    ]
