# Generated by Django 6.1.1 on 2026-09-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='global_only',
            field=models.BooleanField(default=False),
        ),
    ]
